# Get all dags from the DAG folder
GET http://localhost:8080/api/v1/dags HTTP/1.1
Authorization: Basic YWlyZmxvdzphaXJmbG93

###

# Trigge a DAG
# Pass the DAG ID here: /api/v1/dags/<dag-id>/dag_runs
POST http://localhost:8080/api/v1/dags/hello_world/dagRuns HTTP/1.1
Authorization: Basic YWlyZmxvdzphaXJmbG93
content-type: application/json

{
    "conf": {
        "message": "Hello there"
    }
}

# pass `conf` in the request body to be passed on to the DAG
# "conf": {},

###

# Get info of triggered DAG run
GET http://localhost:8080/api/v1/dags/hello_world/dagRuns HTTP/1.1
Authorization: Basic YWlyZmxvdzphaXJmbG93

###

# Get info of a specific DAG run, pass DAG run ID here: /api/v1/dags/<dag-id>/dagRuns/<dag-run-id>
GET http://localhost:8080/api/v1/dags/hello_world/dagRuns/scheduled__2022-05-12T12:00:00+00:00 HTTP/1.1
Authorization: Basic YWlyZmxvdzphaXJmbG93

###